language: node_js
dist: trusty
node_js: stable
sudo: required

install:
  - npm install -g bower
  - npm install
  - bower install
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./
  on:
  branch: master
